"""add content_hash

Revision ID: 9eacd8a6fb8a
Revises: ceaa3342c952
Create Date: 2026-05-06 08:38:59.414216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eacd8a6fb8a'
down_revision: Union[str, Sequence[str], None] = 'ceaa3342c952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_items', sa.Column('content_hash', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_news_items_content_hash'), 'news_items', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_items_content_hash'), table_name='news_items')
    op.drop_column('news_items', 'content_hash')
    # ### end Alembic commands ###
